<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>GLI.Runtime</RootNamespace>
    <ApplicationId>us.cjhowe.glibre.Runtime</ApplicationId>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net10.0-macos;net10.0-ios</TargetFrameworks>
    <SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
  </PropertyGroup>

</Project>
