# Apache Fory C++ — vcpkg overlay port
# Tag:    v0.17.0
# Commit: ad1b286ab61758d4a96618d7e7d0eea9a3c0dc9b
# Upstream: https://github.com/apache/fury
#
# Fory C++ depends on Abseil (absl) for debugging support. The upstream
# CMakeLists.txt fetches Abseil via FetchContent; this portfile patches that
# to use find_package(absl) so vcpkg supplies the dependency cleanly.
#
# The upstream CMake build exports ForyTargets.cmake with the fory:: namespace.
# This portfile adds an alias target Fory::fory so consumers can use the
# capitalised namespace consistent with glibre convention
# (see reviews/decisions/fory-codegen.md).

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO apache/fury
    REF "v${VERSION}"
    SHA512 ce3cf158a184c19e9d7cfa974442846b77e1d893b8231b852b05fbd535ec1c39e30980ab5be513ada1432ef59b163681025088b902a2eb1442282348e54eeb2c
    PATCHES
        patches/0001-use-vcpkg-abseil.patch
)

# Build only the cpp/ subdirectory (the repo root is a multi-language monorepo)
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}/cpp"
    OPTIONS
        -DFORY_BUILD_TESTS=OFF
        -DFORY_BUILD_SHARED=ON
        -DFORY_BUILD_STATIC=ON
        -DFORY_USE_AVX2=OFF
    MAYBE_UNUSED_VARIABLES
        FORY_WARNINGS_AS_ERRORS
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(
    PACKAGE_NAME Fory
    CONFIG_PATH lib/cmake/fory
)

# Remove the debug-only include directory duplicate
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

# Inject Fory::fory alias into the installed package config so that
# Fory::fory (glibre convention) resolves to the upstream fory::fory_lib.
# Note: CMake ALIAS targets are not exported; the real target name in
# ForyTargets.cmake is fory::fory_lib (the backing target of the alias).
file(WRITE "${CURRENT_PACKAGES_DIR}/share/fory/ForyAliases.cmake" [[
# Auto-generated by glibre overlay portfile (refs #218).
# Exports capitalised-namespace aliases required by glibre convention.
# The upstream fory::fory ALIAS target is not exported by CMake's install()
# command; its backing target fory::fory_lib is.  We create interface aliases
# that glibre consumers can use.
#
# Abseil is a non-optional transitive dependency of Fory (used by the
# debugging subsystem).  Declare it here so that consumers fail fast with a
# clear CMake error rather than a cryptic linker error if absl is absent.
include(CMakeFindDependencyMacro)
find_dependency(absl CONFIG REQUIRED)

if(TARGET fory::fory_lib AND NOT TARGET Fory::fory)
    add_library(Fory::fory INTERFACE IMPORTED GLOBAL)
    set_target_properties(Fory::fory PROPERTIES
        INTERFACE_LINK_LIBRARIES "fory::fory_lib"
    )
endif()
if(TARGET fory::fory_serialization_lib AND NOT TARGET Fory::serialization)
    add_library(Fory::serialization INTERFACE IMPORTED GLOBAL)
    set_target_properties(Fory::serialization PROPERTIES
        INTERFACE_LINK_LIBRARIES "fory::fory_serialization_lib"
    )
endif()
if(TARGET fory::fory_row_format_lib AND NOT TARGET Fory::row_format)
    add_library(Fory::row_format INTERFACE IMPORTED GLOBAL)
    set_target_properties(Fory::row_format PROPERTIES
        INTERFACE_LINK_LIBRARIES "fory::fory_row_format_lib"
    )
endif()
]])

# Append the alias include into the generated config file
file(APPEND "${CURRENT_PACKAGES_DIR}/share/fory/ForyConfig.cmake"
    "\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/ForyAliases.cmake\")\n"
)

vcpkg_copy_pdbs()

# Install the license
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

configure_file("${CMAKE_CURRENT_LIST_DIR}/usage"
    "${CURRENT_PACKAGES_DIR}/share/fory/usage"
    COPYONLY
)
