// core/src/plugin_manifest.cpp
//
// PluginManifest::open() — stub implementation.
//
// The full implementation is generated by glibre-foryc as a per-plugin
// manifest.cpp (plan #225).  This stub provides the correct error-path
// behaviour so unit tests can exercise PluginManifestNotFound without
// requiring the codegen pipeline to have run.
//
// Full deserialization (Fory binary decode) lands in plan #225.
// Loader integration (dlopen → manifest-read → hash-check) lands in #229.

#include "glibre/core/plugin_manifest.hpp"

#include <filesystem>
#include <string>

namespace glibre::core {

Result<PluginManifest> PluginManifest::open(const eastl::string& path) {
    // Convert eastl::string to std::filesystem::path for OS stat call.
    // std::filesystem is an explicit std:: carve-out per PHILOSOPHY §11
    // ("std::filesystem" is in the permitted-std list).
    const std::filesystem::path fs_path(path.c_str());

    // Use the error_code overload to avoid potential filesystem_error throws
    // in -fno-exceptions builds.  Any OS error (permissions, etc.) maps to
    // NotFound — the caller cannot distinguish "missing" from "inaccessible"
    // in this stub; the full implementation in plan #225 may refine this.
    std::error_code ec;
    if (!std::filesystem::is_regular_file(fs_path, ec)) {
        return std::unexpected(
            glibre::Error{core::Error::PluginManifestNotFound});
    }

    // Stub: a real file exists at this path but we cannot deserialize it
    // until glibre-foryc emits the Fory decode shim (plan #225).
    // Return Invalid so callers that reach here with a real file get a
    // predictable, diagnosable error rather than UB.
    return std::unexpected(
        glibre::Error{core::Error::PluginManifestInvalid});
}

}  // namespace glibre::core
