// examples/plugin-noop/plugin_noop.cpp
//
// Reference no-op plugin — canonical plugin shape and link-test target.
//
// This plugin exports the four required C symbols documented in
// reviews/decisions/plugin-abi.md §"Plugin file shape":
//
//   1. glibre_plugin_abi_hash    — ABI hash string (placeholder in MVP;
//                                   real value comes from glibre-types codegen).
//   2. glibre_plugin_manifest    — Fory-serialized manifest blob (empty in MVP;
//                                   real blob generated by fory-codegen plan #223/#225).
//   3. glibre_plugin_manifest_size — byte length of the manifest blob.
//   4. glibre_plugin_register    — registration entry-point; registers nothing.
//
// The optional glibre_plugin_unregister is also exported here as an example
// of the full symmetric teardown shape (optional in MVP per plugin-abi.md
// §"Open Questions" point 1).
//
// This file acts as:
//   • A compile-time check that plugin_context.hpp is self-contained.
//   • A link-test target that confirms all four symbols build without error.
//   • A canonical template plugin authors can copy to bootstrap a new plugin.
//
// DO NOT register real components or systems here — this is a no-op stub.
//
// Compilation requirements:
//   C++23, -fno-exceptions, -fvisibility=hidden (entry-points carry
//   GLIBRE_PLUGIN_EXPORT / [[gnu::visibility("default")]] explicitly).

#include <cstddef>
#include <cstdint>

#include <glibre/core/plugin_context.hpp>

// ---------------------------------------------------------------------------
// Symbol 1: glibre_plugin_abi_hash
//
// In production this value is obtained by #include <glibre/types/abi_hash.hpp>
// (generated by the fory-codegen pipeline, plan #223/#225) and re-exporting
// glibre_types_abi_hash()'s value as a string literal.
//
// For this MVP stub we use a sentinel string that the test can match
// symbolically.  The real loader (plan #229) will reject plugins whose
// abi_hash differs from the host's glibre_types_abi_hash(); this stub
// would be refused in a live engine, which is intentional — it is a
// compile/link test, not a shippable plugin.
// ---------------------------------------------------------------------------

extern "C" [[gnu::visibility("default")]]
const char* glibre_plugin_abi_hash =
    // 64 hex chars = 32 blake3 bytes — placeholder zero digest.
    "0000000000000000000000000000000000000000000000000000000000000000";

// ---------------------------------------------------------------------------
// Symbols 2 & 3: glibre_plugin_manifest / glibre_plugin_manifest_size
//
// In production these are generated by the fory-codegen step that processes
// plugins/*/plugin.fory (plan #223/#225), emitting a manifest.cpp that
// embeds the Fory-serialized blob into .rodata.
//
// For this MVP stub the manifest is an empty blob (zero bytes).
// ---------------------------------------------------------------------------

extern "C" [[gnu::visibility("default")]]
const std::byte* glibre_plugin_manifest = nullptr;

extern "C" [[gnu::visibility("default")]]
std::size_t glibre_plugin_manifest_size = 0u;

// ---------------------------------------------------------------------------
// Symbol 4: glibre_plugin_register
//
// The canonical entry-point.  This no-op implementation returns success
// without registering any component, system, pass, or panel.
//
// -Wreturn-type-c-linkage: intentional — std::expected is ABI-safe across the
// middleman dylib boundary (plugin-abi.md §"Registration Entry-Point Signature").
// The pragma is also applied in plugin_entry.hpp; repeat here for the definition.
// ---------------------------------------------------------------------------

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"

extern "C" GLIBRE_PLUGIN_EXPORT
glibre::Result<void>
glibre_plugin_register(glibre::core::PluginContext& /*ctx*/) noexcept {
    // No-op: this reference plugin registers nothing.
    // A real plugin would call ctx.register_component(...), ctx.register_system(...),
    // etc., and return std::unexpected(err) on any failure.
    return {};
}

// ---------------------------------------------------------------------------
// glibre_plugin_unregister (optional in MVP)
//
// Paired teardown symbol.  Mandatory once hot-reload migrations land
// (plugin-abi.md §"Open Questions" point 1).
// ---------------------------------------------------------------------------

extern "C" GLIBRE_PLUGIN_EXPORT
glibre::Result<void>
glibre_plugin_unregister(glibre::core::PluginContext& /*ctx*/) noexcept {
    // No-op: nothing was registered, so nothing to unregister.
    return {};
}

#pragma clang diagnostic pop
