// SPDX-License-Identifier: Apache-2.0
// tools/foryc/src/emit_migration.hpp
//
// Migration-dispatcher emission pass for glibre-foryc (plan #221).
//
// Produces a generated C++ translation unit (migrations.cpp) from a parsed
// Schema IR.  The caller (main.cpp --emit=migration) writes the returned
// string to:
//   <out>/src/<ctx>/<Type>_migrations.cpp
// per the pipeline in reviews/decisions/fory-codegen.md §"Pipeline".
//
// Generated TU structure (per fory-codegen.md §"Migration Mechanic"):
//
//   #include <cstddef>
//   #include <cstdint>
//
//   // Forward-declare each provider symbol.
//   // (The owning context supplies the body; this TU only references it.)
//   extern void* <provider_symbol>;  // placeholder — real sig in owning ctx
//
//   // MigrationEntry — ABI-stable entry in the dispatcher table.
//   // Layout matches glibre/types/migration_entry.hpp (not generated by foryc).
//   struct MigrationEntry {
//       std::uint32_t from_version;
//       std::uint32_t to_version;
//       void* provider;  // function pointer (erased for C-ABI crossing)
//   };
//
//   static const MigrationEntry k_migrations[] = {
//       { 1, 2, reinterpret_cast<void*>(<provider_v1_to_v2>) },
//       { 2, 3, reinterpret_cast<void*>(<provider_v2_to_v3>) },
//   };
//
//   extern "C" const MigrationEntry* glibre_plugin_migrations =
//       (sizeof(k_migrations) > 0) ? k_migrations : nullptr;
//   extern "C" std::size_t glibre_plugin_migrations_size =
//       sizeof(k_migrations) / sizeof(k_migrations[0]);
//
// For schemas with no migration declarations, `k_migrations` is omitted
// and both exported symbols are set to the empty-table forms:
//
//   extern "C" const MigrationEntry* glibre_plugin_migrations = nullptr;
//   extern "C" std::size_t glibre_plugin_migrations_size = 0;
//
// Design notes:
//   - The function `emit_migration` operates on the whole Schema.  Multiple
//     TypeDecl entries in one Schema each emit their own migrations; all
//     entries are concatenated into one TU.
//   - Provider symbols are referenced via forward declaration + cast, not
//     via type-safe function-pointer declarations.  This keeps the generated
//     TU independent of the owning context's headers (no include needed).
//   - `glibre_plugin_migrations` and `glibre_plugin_migrations_size` are
//     the two symbols the plugin loader dereferences at deserialization time.
//
// PHILOSOPHY §11: EASTL replaces std containers/strings in the IR and the
//   returned string.  std:: retained for std::expected (glibre::Result),
//   std::string_view, and std::format.

#pragma once

#include <expected>
#include <string_view>

#include <EASTL/string.h>

#include "glibre/error.hpp"

#include "parser.hpp"

namespace glibre::tools::foryc {

// Emit a C++ migration-dispatcher translation unit for a Schema.
//
// Returns the complete text of a generated .cpp file that:
//   - Forward-declares each provider symbol referenced in MigrationDecl.
//   - Emits a static MigrationEntry table (k_migrations[]).
//   - Exports `extern "C" glibre_plugin_migrations` and
//     `glibre_plugin_migrations_size`.
//
// For schemas with no migration declarations across ALL TypeDecl entries,
// the table is empty and the exported size is 0.
//
// `source_path` is embedded in the generated file's header comment.
//
// Error codes:
//   tools::Error::ForycEmptySchema — schema.types is empty.
//   tools::Error::ForycSyntaxError — malformed IR (empty FQN).
[[nodiscard]] glibre::Result<eastl::string>
emit_migration(const Schema& schema, std::string_view source_path) noexcept;

}  // namespace glibre::tools::foryc
