// SPDX-License-Identifier: Apache-2.0
// tools/foryc/src/emit_header.hpp
//
// Header-emission pass for glibre-foryc (plan #220).
//
// Produces a generated C++ header string from a parsed Schema IR.
// The caller (main.cpp --emit=header) writes the returned string to
//   <out>/include/glibre/types/<ctx>/<Type>.hpp
// per the pipeline in reviews/decisions/fory-codegen.md §"Pipeline".
//
// Design constraints (fory-codegen.md §"ABI Stability Rules"):
//   - Fields in each generated struct are tag-sorted ascending (rule 1).
//   - Every struct is marked `final`; no virtuals; `= default` ctor only
//     (rule 2).
//   - Scalar mapping uses the builtin table from fory-codegen.md §"Rules":
//       u8  → uint8_t,    u16 → uint16_t, u32 → uint32_t, u64 → uint64_t
//       i8  → int8_t,     i16 → int16_t,  i32 → int32_t,  i64 → int64_t
//       f32 → float,      f64 → double
//       bool → bool
//       vec2f → glibre::math::Vec2f   vec3f → glibre::math::Vec3f
//       vec4f → glibre::math::Vec4f   vec2i → glibre::math::Vec2i
//       vec3i → glibre::math::Vec3i   vec4i → glibre::math::Vec4i
//       quatf → glibre::math::Quatf
//       entity → glibre::core::EntityId
//       string → eastl::string        bytes  → eastl::vector<std::byte>
//       list<T> → eastl::vector<T_cpp>
//       map<K,V> → eastl::unordered_map<K_cpp, V_cpp>
//       option<T> → eastl::optional<T_cpp>
//
// PHILOSOPHY §11: EASTL replaces std containers/strings in the IR and in
//   generated code bodies.  std:: retained for std::expected (glibre::Result),
//   std::filesystem, std::string_view.

#pragma once

#include <expected>
#include <string_view>

#include <EASTL/string.h>

#include "glibre/error.hpp"
#include "parser.hpp"

namespace glibre::tools::foryc {

// Emit a C++ header for the type(s) in `schema`.
//
// Returns the complete text of a generated header file containing:
//   - A "generated by glibre-foryc" file comment with source path and a
//     TODO citing #222 for ABI hash insertion.
//   - `#pragma once` guard.
//   - `#include <glibre/types/_builtins.hpp>` when any field resolves to a
//     math or entity builtin type (vec*f, vec*i, quatf, entity).
//   - `#include <EASTL/...>` headers for container types.
//   - One `struct` per TypeDecl, wrapped in namespaces derived from the
//     schema FQN.  Fields are emitted tag-sorted ascending (ABI rule 1).
//   - Each struct marked `final`; `= default` ctor only (ABI rule 2).
//
// In normal glibre-foryc operation (main.cpp --emit=header), this is called
// with a single-TypeDecl Schema (one per-type output file per Pipeline).
// The function also handles multi-TypeDecl schemas for forward-compat.
//
// Error codes:
//   tools::Error::ForycEmptySchema  — schema.types is empty (reject early).
//   tools::Error::ForycUnknownType  — a field type has no C++ mapping.
//   tools::Error::ForycSyntaxError  — internal: empty FQN or malformed IR.
[[nodiscard]] glibre::Result<eastl::string>
emit_header(const Schema& schema) noexcept;

// Translate a single .fory builtin type name to its C++ equivalent.
// Exposed here for unit-testing and future reuse.
//
// Returns ForycUnknownType if `fory_type` has no mapping.
[[nodiscard]] glibre::Result<eastl::string>
map_builtin_to_cpp(std::string_view fory_type) noexcept;

}  // namespace glibre::tools::foryc
