// SPDX-License-Identifier: Apache-2.0
// tools/foryc/src/emit_migration.hpp
//
// Migration-dispatcher emission pass for glibre-foryc (plan #221).
//
// Produces a generated C++ translation unit (migrations.cpp) from a parsed
// Schema IR.  The caller (main.cpp --emit=migration) writes the returned
// string to:
//   <out>/src/<ctx>/<Type>_migrations.cpp
// per the pipeline in reviews/decisions/fory-codegen.md §"Pipeline".
//
// Generated TU structure (per fory-codegen.md §"Migration Mechanic"):
//
//   #include <cstddef>
//   #include <cstdint>
//   #include <expected>
//
//   // Forward-declare glibre::Error without pulling in engine headers.
//   namespace glibre { struct Error; }
//
//   // MigrationEntry — ABI-stable entry in the per-type dispatcher table.
//   // Layout matches glibre/types/migration_entry.hpp (not generated by foryc).
//   struct MigrationEntry {
//       std::uint32_t from_version;
//       std::uint32_t to_version;
//       void* provider;  // type-erased function pointer
//   };
//
//   // Per TypeDecl — one block per schema type:
//
//   // 1. C++ namespace forward-declarations (NOT extern "C") per point 2 of
//   //    fory-codegen.md §"Migration Mechanic":
//   namespace <ctx_ns> {
//     std::expected<void, glibre::Error>
//         migrate_<Type>_v<N>_to_v<M>(const <Type>V<N>&, <Type>V<M>&);
//   }
//
//   // 2. Per-type static table (point 1 of §"Migration Mechanic"):
//   static const MigrationEntry k_migrations_<Type>[] = {
//       { <from>, <to>, reinterpret_cast<void*>(&<ns>::<fn>) },
//   };
//
//   // 3. Per-type exported C-ABI symbols:
//   extern "C" const MigrationEntry* glibre_plugin_migrations_<Type> =
//       k_migrations_<Type>;
//   extern "C" std::size_t glibre_plugin_migrations_<Type>_size = <count>;
//
// For types with no migration declarations the per-type block collapses to:
//
//   extern "C" const MigrationEntry* glibre_plugin_migrations_<Type> = nullptr;
//   extern "C" std::size_t glibre_plugin_migrations_<Type>_size = 0;
//
// Design notes:
//   - fory-codegen.md §"Migration Mechanic" point 1: each type carries its
//     own static migrations table, not a single flat global.  The plugin
//     loader looks up (Type, from_version, to_version) via the per-type
//     symbol.
//   - fory-codegen.md §"Migration Mechanic" point 2: provider signatures are
//     proper C++ (`std::expected<void, glibre::Error>(const VN&, VNplus1&)`)
//     declared in the owning namespace.  extern "C" on a namespace-qualified
//     name is invalid C++ ([dcl.link]/6); the generated forward decls are
//     therefore plain C++ namespace declarations, NOT extern "C".
//   - The MigrationEntry stores providers as void* (type-erased) because
//     each step has distinct argument types (e.g. TransformV1 vs TransformV2).
//     The plugin loader recovers the real type via the deserialize path.
//   - Provider C++ type names are derived from the fqn + version integers:
//     fqn "glibre.core.Transform", from=1, to=2 →
//       namespace glibre::core {
//         std::expected<void, glibre::Error>
//             migrate_Transform_v1_to_v2(const TransformV1&, TransformV2&);
//       }
//   - `glibre::Error` is forward-declared in the TU (not pulled via include)
//     so the generated TU stays self-contained.
//
// PHILOSOPHY §11: EASTL replaces std containers/strings in the IR and the
//   returned string.  std:: retained for std::expected (glibre::Result),
//   std::string_view, and std::format.

#pragma once

#include <expected>
#include <string_view>

#include <EASTL/string.h>

#include "glibre/error.hpp"

#include "parser.hpp"

namespace glibre::tools::foryc {

// Emit a C++ migration-dispatcher translation unit for a Schema.
//
// Returns the complete text of a generated .cpp file that, for each TypeDecl:
//   - Forward-declares each provider as a C++ namespace function with the
//     correct signature per fory-codegen.md §"Migration Mechanic" point 2.
//   - Emits a static per-type MigrationEntry table (k_migrations_<Type>[]).
//   - Exports `extern "C" glibre_plugin_migrations_<Type>` and
//     `extern "C" glibre_plugin_migrations_<Type>_size`.
//
// For types with no migration declarations the per-type table is omitted and
// both exported symbols are set to the empty-table forms (nullptr / 0).
//
// `source_path` is embedded in the generated file's header comment.
//
// Error codes:
//   tools::Error::ForycEmptySchema — schema.types is empty.
//   tools::Error::ForycSyntaxError — malformed IR (empty FQN).
[[nodiscard]] glibre::Result<eastl::string>
emit_migration(const Schema& schema, std::string_view source_path) noexcept;

}  // namespace glibre::tools::foryc
