// SPDX-License-Identifier: Apache-2.0
// tools/foryc/src/emit_migration.hpp
//
// Migration-dispatcher emission pass for glibre-foryc (plan #221).
//
// Produces a generated C++ translation unit (migrations.cpp) from a parsed
// Schema IR.  The caller (main.cpp --emit=migration) writes the returned
// string to:
//   <out>/src/<ctx>/<Type>_migrations.cpp
// per the pipeline in reviews/decisions/fory-codegen.md §"Pipeline".
//
// Generated TU structure (per fory-codegen.md §"Migration Mechanic"):
//
// NOTE: exported C symbol names use the mangled FQN (plan #1010,
// fory-codegen.md §"ABI Stability Rules" point 4).  The dotted FQN is
// mangled by replacing every '.' with '__' (double-underscore) to produce
// a C-identifier suffix (<MangledFQN>).  Example:
//   FQN "glibre.core.Transform" → <MangledFQN> = "glibre__core__Transform"
//
//   #include <cstddef>
//   #include <cstdint>
//   #include <expected>
//   #include "glibre/error.hpp"   // glibre::Error (complete — required by std::expected)
//
//   // MigrationEntry — ABI-stable entry in the per-type dispatcher table.
//   // Layout matches glibre/types/migration_entry.hpp (not generated by foryc).
//   struct MigrationEntry {
//       std::uint32_t from_version;
//       std::uint32_t to_version;
//       void* provider;  // type-erased function pointer
//   };
//
//   // Per TypeDecl — one block per schema type:
//
//   // 1a. Forward-declare the versioned structs in the type's namespace so the
//   //     TU is self-contained even when the generated type headers are not on
//   //     the include path (e.g. in standalone round-trip tests).
//   namespace <type_ns> { struct <Type>V<N>; struct <Type>V<M>; }
//
//   // 1b. C++ namespace forward-declarations (NOT extern "C") per point 2 of
//   //     fory-codegen.md §"Migration Mechanic".
//   //     The fwd-decl is wrapped in the *provider's* namespace (derived from
//   //     mig.provider itself, not from the type's namespace) so that a cross-
//   //     context provider (e.g. type in glibre::core, provider in glibre::physics)
//   //     resolves correctly at link time.  Parameter types are always fully-
//   //     qualified (glibre::core::TransformV1) so the declaration is unambiguous
//   //     in any enclosing namespace.
//   namespace <provider_ns> {
//     std::expected<void, glibre::Error>
//         migrate_<Type>_v<N>_to_v<M>(const <type_ns>::<Type>V<N>&,
//                                      <type_ns>::<Type>V<M>&);
//   }
//
//   // 2. Per-type static table (point 1 of §"Migration Mechanic"):
//   static const MigrationEntry k_migrations_<MangledFQN>[] = {
//       { <from>, <to>, reinterpret_cast<void*>(&<ns>::<fn>) },
//   };
//
//   // 3. Per-type exported C-ABI symbols (emitted for every type, plan #978):
//   extern "C" const std::uint32_t glibre_plugin_current_version_<MangledFQN> = <N>;
//
//   // 4. Migration table pointer + count:
//   extern "C" const MigrationEntry* glibre_plugin_migrations_<MangledFQN> =
//       k_migrations_<MangledFQN>;
//   extern "C" std::size_t glibre_plugin_migrations_<MangledFQN>_size = <count>;
//
// For types with no migration declarations the per-type block collapses to:
//
//   extern "C" const std::uint32_t glibre_plugin_current_version_<MangledFQN> = <N>;
//   extern "C" const MigrationEntry* glibre_plugin_migrations_<MangledFQN> = nullptr;
//   extern "C" std::size_t glibre_plugin_migrations_<MangledFQN>_size = 0;
//
// Design notes:
//   - fory-codegen.md §"Migration Mechanic" point 1: each type carries its
//     own static migrations table, not a single flat global.  The plugin
//     loader looks up (Type, from_version, to_version) via the per-type
//     symbol.
//   - fory-codegen.md §"Migration Mechanic" point 2: provider signatures are
//     proper C++ (`std::expected<void, glibre::Error>(const VN&, VNplus1&)`)
//     declared in the owning namespace.  extern "C" on a namespace-qualified
//     name is invalid C++ ([dcl.link]/6); the generated forward decls are
//     therefore plain C++ namespace declarations, NOT extern "C".
//   - The MigrationEntry stores providers as void* (type-erased) because
//     each step has distinct argument types (e.g. TransformV1 vs TransformV2).
//     The plugin loader recovers the real type via the deserialize path.
//   - Provider C++ type names are derived from the fqn + version integers:
//     fqn "glibre.core.Transform", from=1, to=2 →
//       namespace glibre::core {
//         std::expected<void, glibre::Error>
//             migrate_Transform_v1_to_v2(const TransformV1&, TransformV2&);
//       }
//   - `glibre/error.hpp` is included (not forward-declared) because libc++'s
//     std::expected<void, E> requires E complete on instantiation.  The
//     generated TU is compiled into glibre-types.dylib, which has
//     core/include on its include path; the include is therefore valid.
//   - The provider fwd-decl is wrapped in the *provider's* namespace, derived
//     from the last "::" split in mig.provider, not from the type's namespace.
//     This allows cross-context providers without link errors.
//
// PHILOSOPHY §11: EASTL replaces std containers/strings in the IR and the
//   returned string.  std:: retained for std::expected (glibre::Result),
//   std::string_view, and std::format.

#pragma once

#include <expected>
#include <string_view>

#include <EASTL/string.h>

#include "glibre/error.hpp"

#include "parser.hpp"

namespace glibre::tools::foryc {

// Emit a C++ migration-dispatcher translation unit for a Schema.
//
// Exported C symbol names use the mangled FQN (<MangledFQN>): each '.' in the
// dotted FQN is replaced by '__' (double-underscore) — see fory-codegen.md
// §"ABI Stability Rules" point 4 and plan #1010.
//
// Returns the complete text of a generated .cpp file that, for each TypeDecl:
//   - Exports `extern "C" const std::uint32_t
//       glibre_plugin_current_version_<MangledFQN>`
//     set to `td.version` so the plugin loader can dlsym it (plan #978;
//     fory-codegen.md §"Migration Mechanic" point 1).
//   - Forward-declares each provider as a C++ namespace function with the
//     correct signature per fory-codegen.md §"Migration Mechanic" point 2.
//   - Emits a static per-type MigrationEntry table
//     (k_migrations_<MangledFQN>[]).
//   - Exports `extern "C" glibre_plugin_migrations_<MangledFQN>` and
//     `extern "C" glibre_plugin_migrations_<MangledFQN>_size`.
//
// For types with no migration declarations the per-type table is omitted and
// both exported symbols are set to the empty-table forms (nullptr / 0).
//
// `source_path` is embedded in the generated file's header comment.
//
// Error codes:
//   tools::Error::ForycEmptySchema       — schema.types is empty.
//   tools::Error::ForycSyntaxError       — malformed IR (empty FQN).
//   tools::Error::ForycInvalidIdentifier — a FQN segment contains "__"; the
//       "no __ in segment" invariant is enforced here as a defensive re-check
//       so that callers building IR directly (without the parser) cannot
//       silently produce non-injective mangles.  plan #1010,
//       fory-codegen.md §"ABI Stability Rules" point 4.
[[nodiscard]] glibre::Result<eastl::string>
emit_migration(const Schema& schema, std::string_view source_path) noexcept;

}  // namespace glibre::tools::foryc
