// SPDX-License-Identifier: Apache-2.0
// tools/foryc/src/emit_header.cpp
//
// Implementation of the header-emission pass for glibre-foryc (plan #220).
//
// See emit_header.hpp for the public API and design notes.

#include "emit_header.hpp"

#include <algorithm>
#include <array>
#include <string_view>

#include <EASTL/string.h>
#include <EASTL/vector.h>

namespace glibre::tools::foryc {

namespace {

// -----------------------------------------------------------------------
// Builtin type mapping table
//
// Authority: reviews/decisions/fory-codegen.md §"Rules" bullet list.
// The table is exhaustive for all scalar/composite builtins listed there.
// Generic types (list<T>, map<K,V>, option<T>) are handled separately
// below in map_generic_to_cpp().
// -----------------------------------------------------------------------

struct BuiltinEntry {
    std::string_view fory;
    std::string_view cpp;
};

static constexpr BuiltinEntry k_builtin_map[] = {
    // Unsigned integers
    {"u8",     "uint8_t"},
    {"u16",    "uint16_t"},
    {"u32",    "uint32_t"},
    {"u64",    "uint64_t"},
    // Signed integers
    {"i8",     "int8_t"},
    {"i16",    "int16_t"},
    {"i32",    "int32_t"},
    {"i64",    "int64_t"},
    // Floating-point
    {"f32",    "float"},
    {"f64",    "double"},
    // Boolean
    {"bool",   "bool"},
    // Math aggregates (generated by glibre math library, plan post-MVP)
    {"vec2f",  "glibre::math::Vec2f"},
    {"vec3f",  "glibre::math::Vec3f"},
    {"vec4f",  "glibre::math::Vec4f"},
    {"vec2i",  "glibre::math::Vec2i"},
    {"vec3i",  "glibre::math::Vec3i"},
    {"vec4i",  "glibre::math::Vec4i"},
    {"quatf",  "glibre::math::Quatf"},
    // ECS handle
    {"entity", "glibre::core::EntityId"},
    // Variable-length primitives — EASTL per PHILOSOPHY §11
    {"string", "eastl::string"},
    {"bytes",  "eastl::vector<std::byte>"},
};

// Map the base (non-generic) name.  Returns nullptr if not found.
[[nodiscard]] static const char* lookup_scalar(std::string_view base) noexcept {
    for (const auto& e : k_builtin_map) {
        if (e.fory == base)
            return e.cpp.data();
    }
    return nullptr;
}

// -----------------------------------------------------------------------
// map_generic_to_cpp — handle list<T>, map<K,V>, option<T>
//
// The inner type(s) are recursively translated via map_builtin_to_cpp.
// -----------------------------------------------------------------------

// Forward declaration (defined later in this file as the public API).
[[nodiscard]] glibre::Result<eastl::string>
map_builtin_to_cpp_impl(std::string_view fory_type) noexcept;

// Split "A,B" → {"A", "B"}.  Returns false if the split is ambiguous
// (nested generics with commas — not supported in v1).
[[nodiscard]] static bool split_two(
    std::string_view params,
    std::string_view& out_a,
    std::string_view& out_b) noexcept
{
    // Find the top-level comma (depth 0 in angle brackets).
    int depth = 0;
    for (std::size_t i = 0; i < params.size(); ++i) {
        if (params[i] == '<') ++depth;
        else if (params[i] == '>') --depth;
        else if (params[i] == ',' && depth == 0) {
            out_a = params.substr(0, i);
            out_b = params.substr(i + 1);
            return true;
        }
    }
    return false;
}

// Trim leading/trailing whitespace from a string_view.
[[nodiscard]] static std::string_view trim(std::string_view sv) noexcept {
    while (!sv.empty() && (sv.front() == ' ' || sv.front() == '\t')) sv.remove_prefix(1);
    while (!sv.empty() && (sv.back() == ' ' || sv.back() == '\t')) sv.remove_suffix(1);
    return sv;
}

[[nodiscard]] static glibre::Result<eastl::string>
map_generic_to_cpp(std::string_view base, std::string_view params) noexcept {
    if (base == "list") {
        // list<T> → eastl::vector<T_cpp>
        auto inner = map_builtin_to_cpp_impl(trim(params));
        if (!inner)
            return std::unexpected{inner.error()};
        eastl::string out{"eastl::vector<"};
        out += *inner;
        out += '>';
        return out;
    }
    if (base == "option") {
        // option<T> → eastl::optional<T_cpp>
        auto inner = map_builtin_to_cpp_impl(trim(params));
        if (!inner)
            return std::unexpected{inner.error()};
        eastl::string out{"eastl::optional<"};
        out += *inner;
        out += '>';
        return out;
    }
    if (base == "map") {
        // map<K,V> → eastl::unordered_map<K_cpp, V_cpp>
        std::string_view ka, vb;
        if (!split_two(params, ka, vb))
            return std::unexpected{glibre::Error{tools::Error::ForycSyntaxError}};
        auto key = map_builtin_to_cpp_impl(trim(ka));
        if (!key)
            return std::unexpected{key.error()};
        auto val = map_builtin_to_cpp_impl(trim(vb));
        if (!val)
            return std::unexpected{val.error()};
        eastl::string out{"eastl::unordered_map<"};
        out += *key;
        out += ", ";
        out += *val;
        out += '>';
        return out;
    }
    // Unknown generic base
    return std::unexpected{glibre::Error{tools::Error::ForycUnknownType}};
}

// -----------------------------------------------------------------------
// map_builtin_to_cpp_impl — core translation (called recursively)
// -----------------------------------------------------------------------

[[nodiscard]] glibre::Result<eastl::string>
map_builtin_to_cpp_impl(std::string_view fory_type) noexcept {
    // Strip surrounding whitespace (robustness for recursive calls).
    fory_type = trim(fory_type);

    // Generic type: find the '<' delimiter.
    const std::size_t lt = fory_type.find('<');
    if (lt != std::string_view::npos) {
        const std::string_view base = fory_type.substr(0, lt);
        // params is everything between < and the matching >
        if (fory_type.back() != '>')
            return std::unexpected{glibre::Error{tools::Error::ForycSyntaxError}};
        const std::string_view params = fory_type.substr(lt + 1, fory_type.size() - lt - 2);
        return map_generic_to_cpp(base, params);
    }

    // Scalar lookup
    const char* mapped = lookup_scalar(fory_type);
    if (!mapped)
        return std::unexpected{glibre::Error{tools::Error::ForycUnknownType}};
    return eastl::string{mapped};
}

// -----------------------------------------------------------------------
// FQN decomposition helpers
//
// "glibre.core.Transform" →
//   namespace_parts = ["glibre", "core"]
//   type_name       = "Transform"
// -----------------------------------------------------------------------

struct FqnParts {
    eastl::vector<eastl::string> namespaces;  // all but the last component
    eastl::string type_name;                  // last component
};

[[nodiscard]] static FqnParts decompose_fqn(const eastl::string& fqn) noexcept {
    FqnParts parts;
    std::size_t start = 0;
    while (true) {
        const std::size_t dot = fqn.find('.', start);
        if (dot == eastl::string::npos) {
            parts.type_name = fqn.substr(start);
            break;
        }
        parts.namespaces.push_back(fqn.substr(start, dot - start));
        start = dot + 1;
    }
    return parts;
}

// -----------------------------------------------------------------------
// emit_type_decl — emit one struct for a TypeDecl
// -----------------------------------------------------------------------

[[nodiscard]] static glibre::Result<eastl::string>
emit_type_decl(const TypeDecl& td) noexcept {
    // Sort fields by tag (ascending) — ABI rule 1.
    eastl::vector<const FieldDecl*> sorted;
    sorted.reserve(td.fields.size());
    for (const auto& f : td.fields)
        sorted.push_back(&f);
    std::sort(sorted.begin(), sorted.end(), [](const FieldDecl* a, const FieldDecl* b) {
        return a->tag < b->tag;
    });

    const FqnParts fqn = decompose_fqn(td.fqn);

    eastl::string out;

    // Open namespaces.
    for (const auto& ns : fqn.namespaces) {
        out += "namespace ";
        out += ns;
        out += " {\n";
    }
    if (!fqn.namespaces.empty())
        out += "\n";

    // Struct comment.
    out += "// Generated by glibre-foryc from schema ";
    out += td.fqn;
    out += " v";
    // version as decimal string
    {
        char buf[16];
        const auto n = static_cast<unsigned>(td.version);
        unsigned rem = n;
        int len = 0;
        do { buf[len++] = static_cast<char>('0' + rem % 10); rem /= 10; } while (rem);
        // reverse
        for (int i = 0, j = len - 1; i < j; ++i, --j) {
            const char tmp = buf[i]; buf[i] = buf[j]; buf[j] = tmp;
        }
        out += eastl::string(buf, static_cast<eastl::string::size_type>(len));
    }
    out += "\n";
    out += "// TODO(#222): insert ABI hash here once plan #222 lands.\n";

    // Struct declaration — ABI rule 2: final, no virtuals, = default ctor.
    out += "struct ";
    out += fqn.type_name;
    out += " final {\n";

    // Fields (tag-sorted).
    for (const FieldDecl* fd : sorted) {
        const std::string_view tn(fd->type_name.data(), fd->type_name.size());
        auto cpp_type = map_builtin_to_cpp_impl(tn);
        if (!cpp_type)
            return std::unexpected{cpp_type.error()};

        out += "    ";
        out += *cpp_type;
        out += " ";
        out += fd->name;
        out += "{};\n";
    }

    // Default ctor — ABI rule 2.
    out += "\n";
    out += "    ";
    out += fqn.type_name;
    out += "() = default;\n";
    out += "};\n";

    // Close namespaces (reverse order).
    if (!fqn.namespaces.empty()) {
        out += "\n";
        for (auto it = fqn.namespaces.rbegin(); it != fqn.namespaces.rend(); ++it) {
            out += "}  // namespace ";
            out += *it;
            out += "\n";
        }
    }

    return out;
}

}  // anonymous namespace

// -----------------------------------------------------------------------
// Public API — map_builtin_to_cpp
// -----------------------------------------------------------------------

[[nodiscard]] glibre::Result<eastl::string>
map_builtin_to_cpp(std::string_view fory_type) noexcept {
    return map_builtin_to_cpp_impl(fory_type);
}

// -----------------------------------------------------------------------
// Public API — emit_header
// -----------------------------------------------------------------------

[[nodiscard]] glibre::Result<eastl::string>
emit_header(const Schema& schema) noexcept {
    eastl::string out;

    // File-level header comment.
    out += "// GENERATED FILE — do not edit by hand.\n";
    out += "// Source: ";
    out += schema.source_path;
    out += "\n";
    out += "// Generator: glibre-foryc (plan #220)\n";
    out += "// TODO(#222): ABI hash export not yet wired (plan #222).\n";
    out += "\n";
    out += "#pragma once\n";
    out += "\n";

    // Standard includes needed by the generated struct types.
    out += "#include <cstdint>\n";
    out += "#include <cstddef>\n";       // std::byte
    out += "\n";
    out += "#include <EASTL/optional.h>\n";
    out += "#include <EASTL/string.h>\n";
    out += "#include <EASTL/unordered_map.h>\n";
    out += "#include <EASTL/vector.h>\n";
    out += "\n";
    out += "// Canonical builtin type aliases (fory-codegen.md §\"Rules\").\n";
    out += "// Math types (Vec3f, Quatf, …) and EntityId are forward-declared\n";
    out += "// in glibre/types/_builtins.hpp (post-MVP).\n";
    out += "\n";

    // Emit each type.
    for (const auto& td : schema.types) {
        if (td.fqn.empty())
            return std::unexpected{glibre::Error{tools::Error::ForycSyntaxError}};

        auto type_out = emit_type_decl(td);
        if (!type_out)
            return std::unexpected{type_out.error()};

        out += *type_out;
        out += "\n";
    }

    return out;
}

}  // namespace glibre::tools::foryc
