name: Build
on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Restore
        run: dotnet restore glibre.slnx
      - name: Build
        run: dotnet build glibre.slnx --no-restore -c Release
      - name: Test
        run: dotnet test glibre.slnx --no-build -c Release
